### PR TITLE
Docs: End to end example

### PR DESCRIPTION
**Pull request by abourramouss**
From caten api to code-gen!

### CODE REVIEW

**Comment by abourramouss** [comment]
Hopefully this time commits are added to the history, its a different branch

**Comment by hikettei** [comment]
it is really nice dude

**Comment by abourramouss** [comment]
@hikettei what do you think?

**Comment by hikettei** [comment]
@abourramouss It is exactly what I wanted! very good. Just two things:
- Why don't we write the existence of this file in Readme.md?

**Comment by abourramouss** [comment]
> i will merge this tomorrow when i get up

Will modify the readme so it adds a link to the tutorials

**Pull request merged**
